Available help:
  ABORT                            DECLARE
  ALTER AGGREGATE                  DELETE
  ALTER COLLATION                  DISCARD
  ALTER CONVERSION                 DO
  ALTER DATABASE                   DROP AGGREGATE
  ALTER DEFAULT PRIVILEGES         DROP CAST
  ALTER DOMAIN                     DROP COLLATION
  ALTER EXTENSION                  DROP CONVERSION
  ALTER FOREIGN DATA WRAPPER       DROP DATABASE
  ALTER FOREIGN TABLE              DROP DOMAIN
  ALTER FUNCTION                   DROP EXTENSION
  ALTER GROUP                      DROP FOREIGN DATA WRAPPER
  ALTER INDEX                      DROP FOREIGN TABLE
  ALTER LANGUAGE                   DROP FUNCTION
  ALTER LARGE OBJECT               DROP GROUP
  ALTER OPERATOR                   DROP INDEX
  ALTER OPERATOR CLASS             DROP LANGUAGE
  ALTER OPERATOR FAMILY            DROP OPERATOR
  ALTER ROLE                       DROP OPERATOR CLASS
  ALTER SCHEMA                     DROP OPERATOR FAMILY
  ALTER SEQUENCE                   DROP OWNED
  ALTER SERVER                     DROP ROLE
  ALTER TABLE                      DROP RULE
  ALTER TABLESPACE                 DROP SCHEMA
  ALTER TEXT SEARCH CONFIGURATION  DROP SEQUENCE
  ALTER TEXT SEARCH DICTIONARY     DROP SERVER
  ALTER TEXT SEARCH PARSER         DROP TABLE
  ALTER TEXT SEARCH TEMPLATE       DROP TABLESPACE
  ALTER TRIGGER                    DROP TEXT SEARCH CONFIGURATION
  ALTER TYPE                       DROP TEXT SEARCH DICTIONARY
  ALTER USER                       DROP TEXT SEARCH PARSER
  ALTER USER MAPPING               DROP TEXT SEARCH TEMPLATE
  ALTER VIEW                       DROP TRIGGER
  ANALYZE                          DROP TYPE
  BEGIN                            DROP USER
  CHECKPOINT                       DROP USER MAPPING
  CLOSE                            DROP VIEW
  CLUSTER                          END
  COMMENT                          EXECUTE
  COMMIT                           EXPLAIN
  COMMIT PREPARED                  FETCH
  COPY                             GRANT
  CREATE AGGREGATE                 INSERT
  CREATE CAST                      LISTEN
  CREATE COLLATION                 LOAD
  CREATE CONVERSION                LOCK
  CREATE DATABASE                  MOVE
  CREATE DOMAIN                    NOTIFY
  CREATE EXTENSION                 PREPARE
  CREATE FOREIGN DATA WRAPPER      PREPARE TRANSACTION
  CREATE FOREIGN TABLE             REASSIGN OWNED
  CREATE FUNCTION                  REINDEX
  CREATE GROUP                     RELEASE SAVEPOINT
  CREATE INDEX                     RESET
  CREATE LANGUAGE                  REVOKE
  CREATE OPERATOR                  ROLLBACK
  CREATE OPERATOR CLASS            ROLLBACK PREPARED
  CREATE OPERATOR FAMILY           ROLLBACK TO SAVEPOINT
  CREATE ROLE                      SAVEPOINT
  CREATE RULE                      SECURITY LABEL
  CREATE SCHEMA                    SELECT
  CREATE SEQUENCE                  SELECT INTO
  CREATE SERVER                    SET
  CREATE TABLE                     SET CONSTRAINTS
  CREATE TABLE AS                  SET ROLE
  CREATE TABLESPACE                SET SESSION AUTHORIZATION
  CREATE TEXT SEARCH CONFIGURATION SET TRANSACTION
  CREATE TEXT SEARCH DICTIONARY    SHOW
  CREATE TEXT SEARCH PARSER        START TRANSACTION
  CREATE TEXT SEARCH TEMPLATE      TABLE
  CREATE TRIGGER                   TRUNCATE
  CREATE TYPE                      UNLISTEN
  CREATE USER                      UPDATE
  CREATE USER MAPPING              VACUUM
  CREATE VIEW                      VALUES
  DEALLOCATE                       WITH
