## Snap of database.yml
development:
  adapter: postgresql
  encoding: unicode
  database: imageshare_development
  host: localhost
  username: imageshare
  pool: 5

## Snap of database.yml
test:
  adapter: postgresql
  encoding: unicode
  database: imageshare_test
  host: localhost
  username: imageshare
  pool: 5
